"""
Core Pydantic Schemas for the MILES API.

These models define the contract for our API, ensuring data is
validated, structured, and well-documented.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class UserRequest(BaseModel):
    """
    The input model for a user's prompt to the MILES system.
    """

    prompt: str = Field(..., description="Raw user instruction for the Orchestrator brain.")
    user_id: Optional[str] = Field(
        "default-user",
        description="Identifier for telemetry or personalization experiments.",
    )


class OrchestratorTask(BaseModel):
    """
    A single sub-task decomposed by the Orchestrator.
    """

    worker_name: str = Field(..., description="Registered worker identifier (e.g., 3D_Generator).")
    prompt: str = Field(..., description="Worker-specific instruction derived via CoT reasoning.")


class OrchestratorPlan(BaseModel):
    """
    The full plan (task graph) generated by the Orchestrator.
    """

    tasks: List[OrchestratorTask] = Field(
        default=[], description="Ordered execution list for the task queue."
    )
    direct_response: Optional[str] = Field(
        None, description="Immediate answer generated without dispatching to workers."
    )


class TaskDispatchResponse(BaseModel):
    """
    The immediate, non-blocking response sent to the user.
    """

    message: str = Field(..., description="Acknowledgment that tasks were dispatched.")
    task_ids: List[str] = Field(..., description="Celery task identifiers for downstream tracking.")
    plan: OrchestratorPlan = Field(..., description="Echo of the orchestrator's CoT decomposition.")
    direct_response: Optional[str] = Field(
        None,
        description="Immediate answer generated without dispatching to workers.",
    )

